using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryWithBlazorUpdate.Components.Models
{
    public class Movie : LibraryItem
    {
        // additional movie properties
        public int Duration { get; set; } // minutes

        public enum MovieType { DVD, BlueRay, VHS, Film }
        public MovieType type { get; set; }

        public Movie() { }

        public Movie(int movieId, string title, string description, string author, int publishedYear, bool isAvailable, int duration, MovieType type)
        {
            // movieId parameter retained for compatibility with existing call-sites,
            // but primary key is inherited Id (generated by EF)
            base.title = title;
            base.description = description;
            base.publishedYear = publishedYear;
            base.isAvailable = isAvailable;
            base.author = author;
            this.Duration = duration;
            this.type = type;
        }
    }
}
