// <auto-generated />
using System;
using LibraryWithBlazorUpdate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryWithBlazorUpdate.Migrations
{
    [DbContext(typeof(LibraryWithBlazorUpdateContext))]
    [Migration("20260311154214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.LibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("publishedYear")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("title");

                    b.ToTable("LibraryItems");

                    b.HasDiscriminator().HasValue("LibraryItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LibraryItemId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isOverdue")
                        .HasColumnType("bit");

                    b.Property<bool>("isReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("loanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("returnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId");

                    b.HasIndex("MemberId");

                    b.HasIndex("isReturned");

                    b.HasIndex("loanDate");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Member", b =>
                {
                    b.Property<string>("memberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("memberName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("memberSince")
                        .HasColumnType("datetime2");

                    b.HasKey("memberId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Book", b =>
                {
                    b.HasBaseType("LibraryWithBlazorUpdate.Components.Models.LibraryItem");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Magazine", b =>
                {
                    b.HasBaseType("LibraryWithBlazorUpdate.Components.Models.LibraryItem");

                    b.Property<string>("company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue("Magazine");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Movie", b =>
                {
                    b.HasBaseType("LibraryWithBlazorUpdate.Components.Models.LibraryItem");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Loan", b =>
                {
                    b.HasOne("LibraryWithBlazorUpdate.Components.Models.LibraryItem", "item")
                        .WithMany("loans")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryWithBlazorUpdate.Components.Models.Member", "member")
                        .WithMany("loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("item");

                    b.Navigation("member");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.LibraryItem", b =>
                {
                    b.Navigation("loans");
                });

            modelBuilder.Entity("LibraryWithBlazorUpdate.Components.Models.Member", b =>
                {
                    b.Navigation("loans");
                });
#pragma warning restore 612, 618
        }
    }
}
